language: generic 
sudo: required
services:
    - docker
before_install:
    - docker run -e CI=true -t svvpro/client3 -f Deokerfile.dev  . 
scripts:
    - docker run -t svvpro/client3 npm run test -- --coverage
